_target_: src.model.mld_denoiser.MldDenoiser
text_encoded_dim: 768
ff_size: 1024
num_layers: 9
num_heads: 4
dropout: 0.1
normalize_before: False
activation: 'gelu'
flip_sin_to_cos: True
return_intermediate_dec: False
position_embedding: 'mld'
arch: trans_enc
freq_shift: 0
condition: ${model.condition}
latent_dim: ${model.latent_dim}
guidance_scale: ${model.diff_params.guidance_scale}
guidance_uncondp: ${model.diff_params.guidance_uncondp}
nfeats: ${model.nfeats} # TODO FIX THIS
