modelname: basic_clip
_target_: src.model.base_diffusion.MD

latent_dim: 512

ff_size: 1024
num_layers: 9
num_head: 4
droupout: 0.1
activation: "gelu"
render_vids_every_n_epochs: 100
num_vids_to_render: 2
lr_scheduler: null # reduceonplateau, steplr

# normalization
statistics_path: ${statistics_path}
norm_type: standardize # min_max standardize

# diffusion related
diff_params:
  num_inference_timesteps: 200
  prob_uncondp: 0.1 # 0.1 0.25
  prob_drop_text: 0.05 # 0.1 0.25
  prob_drop_motion: 0.05
  guidance_scale_text: 2.5 #
  guidance_scale_motion: 2.0

motion_condition: null
source_encoder: null # trans_enc 
condition: text
smpl_path: ${data.smplh_path}

nfeats: 135
dim_per_feat: [135]
# data related
input_feats:
- "body_transl_delta_pelv"
# - "body_pose_delta"
# - "body_transl"
- "body_orient"
- "body_pose"
# [body_transl_delta_pelv_xy, body_orient_delta, body_pose_delta]
# [body_transl, body_orient, body_pose]

loss_on_positions: false
loss_on_verts: false

scale_loss_on_positions: 500

loss_func_pos: mse # l1 mse
loss_func_feats: mse # l1 mse

defaults:
  # diffusion stuff
  - _self_
  - /path@path
  - train_scheduler: ddpm
  - infer_scheduler: ddpm
  - denoiser: denoiser
  - text_encoder: clipenc #t5_enc  # distilbert_enc # t5_enc
  - motion_condition_encoder: actor
  - losses: basic
  - optim: adamw
  - /model/losses/function/recons@func_recons
  - /model/losses/function/recons@func_latent
  - /model/losses/function/kl@func_kl
