modelname: basic
_target_: src.model.base_diffusion.MD
latent_dim: 256
vae: true

ff_size: 1024
num_layers: 9
num_head: 4
droupout: 0.1
activation: "gelu"
render_vids_every_n_epochs: 20
num_vids_to_render: 2
lr_scheduler: null # reduceonplateau, steplr

# normalization
statistics_path: ${statistics_path}
norm_type: standardize # min_max standardize

# diffusion related
diff_params:
  num_inference_timesteps: 1000
  guidance_uncondp: 0.1 # 0.1 0.25
  guidance_scale: 7.5 #

motion_condition: target
condition: text
smpl_path: ${data.smplh_path}

nfeats: 135
dim_per_feat: [135]
# data related
input_feats:
# - "body_transl_delta_pelv_xy"
# - "body_orient_delta"
# - "body_pose_delta"
- "body_transl"
- "body_orient"
- "body_pose"
# [body_transl_delta_pelv_xy, body_orient_delta, body_pose_delta]
# [body_transl, body_orient, body_pose]

loss_on_positions: false

defaults:
  # diffusion stuff
  - train_scheduler: ddpm
  - infer_scheduler: ddpm
  - denoiser: denoiser
  # VAE stuff
  - text_encoder: distilbert_enc
  - motion_encoder: actor
  - motion_decoder: actor
  - losses: basic
  - optim: adamw
  - /model/losses/function/recons@func_recons
  - /model/losses/function/recons@func_latent
  - /model/losses/function/kl@func_kl
