modelname: basic
_target_: src.model.base_diffusion.MD
latent_dim: 256
vae: true

ff_size: 1024
num_layers: 6
num_head: ${model.num_layers}
droupout: 0.1
activation: "gelu"
nvids_to_save: ${callback.render.nvids_to_save}
lr_scheduler: null # reduceonplateau, steplr
diff_params:
  num_inference_steps: 100
  eta: 40
  guidance_scale: 7.5 #
  guidance_uncondp: 0.1 # 0.1 0.25

motion_branch: true
teacher_forcing: false
separate_latents: false

defaults:
  - textencoder: distilbert_enc
  - motionencoder: actor
  - motiondecoder: actor
  - losses: basic
  - optim: adamw
  - /model/losses/function/recons@func_recons
  - /model/losses/function/recons@func_latent
  - /model/losses/function/kl@func_kl
