name: clip_text_encoder
_target_: src.model.textencoder.clip_encoder.ClipTextEncoder
variant: clip_hidden
finetune: false # if false, model weights are frozen
last_hidden_state: true # if true, the last hidden state is used as the text embedding
modelpath: ${path.deps}/clip-vit-large-patch14
