_target_: src.model.textencoder.clip_encoder.ClipTextEncoder
variant: clip
finetune: false # if false, model weights are frozen
last_hidden_state: false # if true, the last hidden state is used as the text embedding
modelpath: ${path.deps}/clip-vit-large-patch14
