hydra:
  run:
    dir: .
  job:
    chdir: true
  output_subdir: null

folder: ???
savedir: null
mean: false
fact: 1
number_of_samples: 1
ckpt_name: 999
last_ckpt_path: ${get_last_checkpoint:${folder},${ckpt_name}}
logger_level: INFO

# scheduler related 
scheduler:
  name: ddpm
  num_inference_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: 'scaled_linear' # ['linear', 'scaled_linear', 'squaredcos_cap_v2']
  clip_sample: false # clip sample to -1~1
  prediction_type: sample


defaults:
  - /path@path
  - override hydra/job_logging: rich # custom
  - override hydra/hydra_logging: rich # custom
  - _self_
