hydra:
  run:
    dir: .
  job:
    chdir: true
  output_subdir: null

folder: ???
savedir: null
mean: false
fact: 1
number_of_samples: 1
ckpt_name: 999
last_ckpt_path: ${get_last_checkpoint:${folder},${ckpt_name}}
logger_level: INFO

defaults:
  - /path@path
  - override hydra/job_logging: rich # custom
  - override hydra/hydra_logging: rich # custom
  - _self_
