hydra:
  run:
    dir: .
  job:
    chdir: true
  output_subdir: null



folder: ???
mode: denoise # denoise / sample / sthing else

savedir: null
mean: false
fact: 1
number_of_samples: 1
ckpt_name: 'last'
last_ckpt_path: ${get_last_checkpoint:${folder},${ckpt_name}}
logger_level: INFO
save_pkl: true
render_vids: false

steps: 1000
guidance_scale_text: 2.5 #
guidance_scale_motion: 1.5
init_from: 'noise' # source

defaults:
  - _self_
  - model/infer_scheduler: ddpm
  - /path@path
  - override hydra/job_logging: rich # custom
  - override hydra/hydra_logging: rich # custom00 

split_to_load: 
- "test"

datapath: ${path.data}/humanml3d_processed # amass_bodilex.pth.tar

