hydra:
  run:
    dir: .
  job:
    chdir: true
    env_set:
      WANDB_API_KEY: '90e13be46265667b13415a5e6d248ae91ab399fc'
      HYDRA_FULL_ERROR: 1
      WANDB__SERVICE_WAIT: 300
  output_subdir: null


folder: ???
mode: sample # denoise / sample / sthing else

savedir: null
mean: false
fact: 1
number_of_samples: 1
ckpt_name: 699 # 'all'
last_ckpt_path: ${get_last_checkpoint:${folder},${ckpt_name}}
logger_level: INFO
render_vids: false
steps: 1000
guidance_scale_text: 2.5 #
guidance_scale_motion: 1.5
init_from: source # noise
condition_mode: full_cond # 'mot_cond' 'text_cond'
subset: test

defaults:
  - _self_
  - model/infer_scheduler: ddpm
  - data: bodilex
  - evaluator: edit_evaluator
  - /path@path
  - override hydra/job_logging: rich # custom
  - override hydra/hydra_logging: rich # custom

split_to_load: 
- "test"
