hydra:
  run:
    dir: .
  job:
    chdir: true
  output_subdir: null

folder: ???

savedir: null
mean: false
fact: 1
number_of_samples: 1
ckpt_name: 'last'
last_ckpt_path: ${get_last_checkpoint:${folder},${ckpt_name}}
logger_level: INFO
save_pkl: false
render_vids: true
subset: null

num_sampling_steps: 1000
guidance_scale_text: null

init_from: 'noise' # noise
condition_mode: 'full_cond' # 'mot_cond' 'text_cond'

defaults:
  - _self_
  - data: hml3d
  - /path@path
  - override hydra/job_logging: rich # custom
  - override hydra/hydra_logging: rich # custom

split_to_load: 
- "test"
- "val"
