hydra:
  run:
    dir: .
  job:
    chdir: true
  output_subdir: null

folder: ???
mode: sample # denoise / sample / sthing else

savedir: null
mean: false
fact: 1
number_of_samples: 1
ckpt_name: 'last'
last_ckpt_path: ${get_last_checkpoint:${folder},${ckpt_name}}
logger_level: INFO

num_sampling_steps: 1000
guidance_scale_text: 2.5 #
guidance_scale_motion: 1.5

init_from: 'noise' # noise
inpaint: false

defaults:
  - _self_
  - model/infer_scheduler: ddpm
  - data: hml3d
  - /path@path
  - override hydra/job_logging: rich # custom
  - override hydra/hydra_logging: rich # custom

split_to_load: 
- "test"
